### ISSUE TITLE
Add lower quartile to wages (ASHE) data

### ISSUE THREAD

**Issue by luke-strange** [open-innovations/jrf-insight#104]
I want to recreate the chart that shows ratio of lower quartile rents to lower quartile earnings per geography:

![Image](https://github.com/open-innovations/jrf-insight/assets/92686634/edc5bcd5-7a00-4d25-8736-fcbab534e1fc)

I need the LQ wages data to do this.

Also, wages are weekly, but rents are monthly. I can grossly assume monthly wage is 4*weekly, but if monthly data exists, then this would be good to use.

TODO:
- [x] add lower quartile weekly wages to `data/ashe/ashe.csv`. 
- [x] Check if monthly wage data exists.

Nice to have:
- [ ] Time series data. (If we can't or don't yet have this, I can put the data on a map for now rather than line chart.)

**Comment by ChristianSpence** [comment]
ASHE data available at weekly, monthly, annual intervals. Will extract LQ monthly data. Do you need annual for house sale prices a well?

**Comment by luke-strange** [comment]
@ChristianSpence that would be useful yes. Thanks.

**Comment by ChristianSpence** [comment]
Re-opening as I'll sort the time series data out, too.
