### ISSUE TITLE
Discuss what to deliver for first-worst MVP to show at next catch-up

### ISSUE THREAD

**Issue by ChristianSpence** [open-innovations/jrf-insight#11]

**Comment by luke-strange** [comment]
Continuing discussion tomorrow!

**Comment by gilesdring** [comment]
So far to raise tickets for:

- [ ] Create initial site - barebones wireframe
- [ ] Visualise "some data"
- [ ] Record 'how to use project board' video
- [ ] ???

**Comment by gilesdring** [comment]
Are all these ticketed, and can we consequently close this ticket? @luke-strange @ChristianSpence
