### ISSUE TITLE
Create initial visualisations of data

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/jrf-insight#16]

**Comment by luke-strange** [comment]
- [ ] Added  aline chart for Y&H.
- [ ] Going to add hex map for NE
- [ ] Bar chart for NW.

**Comment by luke-strange** [comment]
This ticket was dependent on #15 and required some set-up. Initially, this meant the visualisations took slightly longer, but now we have a working example of the main charts, future versions will be about 10x faster.

**Comment by luke-strange** [comment]
@gilesdring need help fixing the colours and labelling.
