### ISSUE TITLE
Recreate example JRF poverty data for the North.

### ISSUE THREAD

**Issue by luke-strange** [open-innovations/jrf-insight#2]
https://www.jrf.org.uk/data?f%5B0%5D=field_taxonomy_poverty_indicator%3A915

See above for the example. Initial step is to recreate this figure (or at least get the data) for the north of England. 

![Image](https://user-images.githubusercontent.com/92686634/235700806-874f2742-159e-4d25-b604-97db1ae74405.png)

What is better approach 
a) extract national data and then filter in a "prepare" stage (bit more future-proof in terms of expanding work)
b) extract local data and present with less prep? (Less fiddly but less future proof)

**Comment by luke-strange** [comment]
Seems the split is by different age groups (Children, working age adults with/without kids), pensioners, and all people. 
Goes back to 1994/95.

**Comment by gilesdring** [comment]
Depends on open-innovations/oi-lume-charts#26 for dashed / dotted lines

**Comment by ChristianSpence** [comment]
Depends on #11 to scope initial MVP

**Comment by luke-strange** [comment]
Need time series data for this, but need to solve #59 first.

**Comment by luke-strange** [comment]
This is complete - its at regional level, and has pensioners, working-age, and children categories.
