### ISSUE TITLE
Review Accessible Numbers for principles to apply to site

### ISSUE THREAD

**Issue by ChristianSpence** [open-innovations/jrf-insight#25]
Worth reviewing as a general concept.

[accessiblenumbers.com](https://accessiblenumbers.com)

**Comment by luke-strange** [comment]
We want to make this into a blog post. Challenged by JRF to present things not just as a percentage. Here's what we came up with: https://jsfiddle.net/gilesdring/hjevnud0/

**Comment by gilesdring** [comment]
Turn this into a style guide (as an MD file) in the repo

**Comment by gilesdring** [comment]
Added to https://github.com/open-innovations/jrf-insight/blob/main/resources/Accessible%20Numbers.md
