### ISSUE TITLE
Add standard demographic summary to place pages

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/jrf-insight#34]
Depends on #33

**Comment by gilesdring** [comment]
Need to update this with list of standard place-based metrics:

1. Population
2. Number of households
3. Population density
4. Geographic area
5. GVA

Poverty related stats:

1. Aggregate IMD
2. Number of children in poverty
3. Households in poverty
4. Unemployment

**Comment by gilesdring** [comment]
@ChristianSpence Where are we up to with this?

**Comment by luke-strange** [comment]
Just need to add unemployment for this to be completed

**Comment by ChristianSpence** [comment]
Good spot - had missed that.

Unemployment (along with economic activity and inactivity) for LAD upwards
(but not CAUTH or NORTH - that's for tomorrow) now in `data/labour-market'
