### ISSUE TITLE
Ensure WGS coordinates used for the geojson pipelines

### ISSUE THREAD

**Issue by luke-strange** [open-innovations/jrf-insight#41]
Stuart and I had to fix "The North" geojson because it used an outdated coordinate system. In ~2018, they enforced that you use WGS (latitude and longitude) to make the file user's life easier. We used QGIS to convert it, but might be other ways you know how to do this @ChristianSpence Christian.

Lume currently requires the geojsons in `.json` format, not `.geojson`. Are we able to fix this @gilesdring ?

Final point: we're limiting to 5dp in the coords. This will be fine for the latitude we are at (roughly 50cm), and reduces the file size considerably.

**Comment by gilesdring** [comment]
Fixed the .geojson issue - I discussed with Stuart yesterday, and the fix is adding the following to `_config.ts`

```ts
import jsonLoader from "lume/core/loaders/json.ts";

site.loadData([".geojson"], jsonLoader);
```

**Comment by luke-strange** [comment]
Closing as the .geojson file format is now useable, and the rest of this ticket is captured in #41
