### ISSUE TITLE
Need to agree the detailed structure of the geographic tree

### ISSUE THREAD

**Issue by ChristianSpence** [open-innovations/jrf-insight#43]
Question: what should come below region?

Obviously we start with:
- The North
- Region

but what comes next?

Should it be county and combined authorities? If so, there will be some small unitary areas (UTLAs) that aren't caught in this (e.g. City of York, Cheshire East).

We could to Counties and UTLAs, but that would give us, e.g. all 5 West Yorkshire districts on the same tier as North Yorkshire. Is this what we want? It feels that CAs (or Metropolitan Counties) should be represented as an equivalent level to counties, so that lower-tier LAs (e.g. Blackburn with Darwen, Blackpool) appear on the same layer as districts within West Yorkshire, Greater Manchester etc.

I'll build a quick mock-up of how this might work

**Comment by ChristianSpence** [comment]
[Example leaflet interactive here](https://christianspence.github.io/geography_tree_examples.html)

One thought: if we go regions > counties/CAs, then some unitaries are not visible. Also, that will mean some "layers" of geographies might be missing in the tree. Question: does this matter?

E.g.:

Region | County | CA | LA
-|-|-|-
Yorkshire & Humber | North Yorkshire | NA | Scarborough
Yorkshire & Humber | NA | West Yorkshire | Calderdale

Guess we could code an 
```
if (is.na([next_level_of_geog_down)) {
  [go_to_next_level_down]
}
```
Could do with @gilesdring and @luke-strange thoughts

**Comment by ChristianSpence** [comment]
Update version is now [here](/data/geo/geographic_lookup.csv)

**Comment by ChristianSpence** [comment]
- [ ] Need to remove *NM fields from geography_tree and create a separate .csv with *CD, *NM as lookup

**Comment by gilesdring** [comment]
Is this basically done?
