### ISSUE TITLE
Change format of `*.geojson`

### ISSUE THREAD

**Issue by ChristianSpence** [open-innovations/jrf-insight#45]
All geojson boundary files should be:
- [x] converted to WGS84
- [x] have `lat` and `long` rounded to 5 decimal places
- [x] be filtered to only those places within `The North`? Is this right?

**Comment by luke-strange** [comment]
Yes, that's the criteria we need!

**Comment by gilesdring** [comment]
Have checked - the GeoJSON files are still in sub-atomic rounding format (e.g. `[ -2.134127018001729, 53.685718815007924 ]`)

**Comment by ChristianSpence** [comment]
I'll sort the rounding out now - did we agree 5dp?
@gilesdring, are you saying we just don't need the CRS object in the json?

**Comment by gilesdring** [comment]
I think that's the case.

According to https://datatracker.ietf.org/doc/html/rfc7946#page-12

  o  Specification of coordinate reference systems has been removed, i.e., the "crs" member of [GJ2008] is no longer used.

**Comment by gilesdring** [comment]
And yes, 5dp longitude is about 1m at the equator

**Comment by ChristianSpence** [comment]
Completed and pushed in 36bf1d8
