### ISSUE TITLE
Adjust leaflet maps to have alpha <1

### ISSUE THREAD

**Issue by ChristianSpence** [open-innovations/jrf-insight#50]

**Comment by luke-strange** [comment]
Spoke to Stuart about this and had a few thoughts:
 1) we can add labels for places over the top. this feature is already implemented so saves stuart extra work.
 2) we should probably move to normal svg maps rather than zoomable ones as this will lighten the site.

**Comment by luke-strange** [comment]
I have switched to SVG maps, and we are working on generate a list of places to lay over the top of each svg map (see #80)

**Comment by luke-strange** [comment]
Stuart has added this feature if we want to use it.
