### ISSUE TITLE
Design and implement the stats block for place

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/jrf-insight#55]
Consider a more tabular format. Top-trumps style

Are there still headlines to draw out, or is this more for the spotlights? Is overall page in a sidebar?

**Comment by luke-strange** [comment]
have created an initial attempt at this. 

![Image](https://github.com/open-innovations/jrf-insight/assets/92686634/43623b56-3fce-4772-a3cc-5b3465c3e621)

things to think about are
- where do we want this on the page?
- how do we keep it simple and easy to look at.

**Comment by luke-strange** [comment]
We've updated the styling: 




![Image](https://github.com/open-innovations/jrf-insight/assets/92686634/4810804f-1a29-48d3-90ad-8d10df972d57)
