### ISSUE TITLE
Fix issue with link from map popup

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/jrf-insight#56]
Map popup does not have a prefix (added by `base_path`)

**Comment by luke-strange** [comment]
Think this is fixed @gilesdring ?

**Comment by gilesdring** [comment]
Resolved (temporarily!) by using a relative path, rather than absolute path.

So rather than the popup linking to `/place/XYZ`, it links to `../place/XYZ`

This might break if the tooltip is ever used elsewhere, but works OK for now!
