### ISSUE TITLE
Outline the potential data contents of each spotlight page

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/jrf-insight#58]

**Comment by gilesdring** [comment]
As discussed in #54 - @luke-strange will add notes from Miro board in to empty pages

**Comment by luke-strange** [comment]
Miro board notes added. I will add links to datasets where I can.

**Comment by luke-strange** [comment]
For now these links will point to the jrf repo. It's worth discussing whether these should point to the original source, or both. I will raise a ticket for this.

**Comment by luke-strange** [comment]
I've added everything from the miro board and links to our current data. need to find data for the other metrics. links to #60
