### ISSUE TITLE
Padding around maps

### ISSUE THREAD

**Issue by luke-strange** [open-innovations/jrf-insight#97]
![Image](https://github.com/open-innovations/jrf-insight/assets/92686634/83b172ec-8f65-426b-86cd-5f63c58b6aa1)

- [x] Adding padding so maps dont go to the edges.

- [x] Move legend off the map to ensure you can always see it.

**Comment by luke-strange** [comment]
@slowe would be good to speak to you about this.

**Comment by slowe** [comment]
@luke-strange Sure. The padding is something that should be done in the JRF site styles.

What kind of map is this? Is it SVG or zoomable?

**Comment by luke-strange** [comment]
1) We want to add padding around the data, so that there is more grey (or white) around the areas of map with data. We want to do this so that we can put the legend somewhere where the background behind it will always be the same colour. Otherwise it can be hard to see. 
 
2) It's an SVG map.
@slowe

**Comment by luke-strange** [comment]
This is now done - need to wait for new release of lume charts and add in `padding:` and `legend:'top'` to all maps visualisations.

**Comment by slowe** [comment]
I added the new release v0.13.1 to the dev branch.
